import = [
  # "~/.config/alacritty/catppuccin-latte.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/everforest.toml"
  # "~/.config/alacritty/onelight.toml"
]

[font]
size = 17.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"

[font.offset]
x = 0
y = 6

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "CreateNewWindow"

[mouse]
hide_when_typing = true

[shell]
program = "/opt/homebrew/bin/fish"

[window]
startup_mode = "Maximized"
# decorations = "buttonless"
dynamic_padding = true
resize_increments = true
option_as_alt = "OnlyLeft"
# opacity = 0.8
# blur = true

# [window.padding]
# x = 10
# y = 10
