# Taken from nord-tmux and modified for the Tokyo Night
# https://github.com/arcticicestudio/nord-tmux
#+----------------+
#+ Plugin Support +
#+----------------+
#+--- tmux-prefix-highlight ---+
set -g @prefix_highlight_fg black
set -g @prefix_highlight_bg brightcyan

#+---------+
#+ Options +
#+---------+
set -g status-interval 1
set -g status on

#+--------+
#+ Status +
#+--------+
#+--- Layout ---+
set -g status-justify left

#+--- Colors ---+
set -g status-style bg='#1f2335',fg=white

#+-------+
#+ Panes +
#+-------+
set -g pane-border-style fg=black
set -g pane-active-border-style fg=brightblack

#+------------+
#+ Clock Mode +
#+------------+
setw -g clock-mode-colour blue

#+----------+
#+ Messages +
#+---------+
set -g message-style fg=white,bg='#1f2335'
set -g message-command-style fg=white,bg='#1f2335'

#+--- tmux-prefix-highlight ---+
set -g @prefix_highlight_output_prefix "#[fg=brightcyan]#[bg=black]#[nobold]#[noitalics]#[nounderscore]#[bg=brightcyan]#[fg=black]"
set -g @prefix_highlight_output_suffix ""
set -g @prefix_highlight_copy_mode_attr "fg=brightcyan,bg=black,bold"

set -g status-left "#[fg=black,bg=blue] #S #[fg=blue,bg=#1f2335,nobold,noitalics,nounderscore]"
set -g status-right "#{prefix_highlight}#[fg=brightblack,bg=#1f2335,nobold,noitalics,nounderscore]#[fg=blue,bg=brightblack] %Y-%m-%d #[fg=blue,bg=brightblack,nobold,noitalics,nounderscore]#[fg=blue,bg=brightblack] %H:%M #[fg=blue,bg=brightblack,nobold,noitalics,nounderscore]#[fg=black,bg=blue] #H "

set -g window-status-format "#[fg=#1f2335,bg=brightblack,nobold,noitalics,nounderscore] #[fg=blue,bg=brightblack]#I #[fg=blue,bg=brightblack,nobold,noitalics,nounderscore] #[fg=blue,bg=brightblack]#W #F #[fg=brightblack,bg=#1f2335,nobold,noitalics,nounderscore]"
set -g window-status-current-format "#[fg=#1f2335,bg=green,nobold,noitalics,nounderscore] #[fg=black,bg=green]#I #[fg=black,bg=green,nobold,noitalics,nounderscore] #[fg=black,bg=green]#W #F #[fg=green,bg=#1f2335,nobold,noitalics,nounderscore]"
set -g window-status-separator ""

