# Taken from nord-tmux and modified for the Tokyo Night
# https://github.com/arcticicestudio/nord-tmux
#+----------------+
#+ Plugin Support +
#+----------------+
#+--- tmux-prefix-highlight ---+
set -g @prefix_highlight_fg black
set -g @prefix_highlight_bg brightcyan

#+---------+
#+ Options +
#+---------+
set -g status-interval 1
set -g status on

#+--------+
#+ Status +
#+--------+
#+--- Layout ---+
set -g status-justify left

#+--- Colors ---+
# set -g status-bg black
# set -g status-fg white
# set -g status-bg
# set -g status-fg
set -g status-style bg='#1f2335',fg='#a9b1d6'


#+-------+
#+ Panes +
#+-------+
set -g pane-border-style bg=black,fg=black
set -g pane-active-border-style bg=black,fg='#1f2335'
set -g display-panes-colour '#1f2335'
set -g display-panes-active-colour '#1f2335'

#+------------+
#+ Clock Mode +
#+------------+
setw -g clock-mode-colour '#7aa2f7'

#+----------+
#+ Messages +
#+---------+
set -g message-style fg='#a9b1d6',bg='#1f2335'
set -g message-command-style fg='#a9b1d6',bg='#1f2335'
# set-option -g message-style bg='#9ece6a',fg=black

#+--- tmux-prefix-highlight ---+
set -g @prefix_highlight_output_prefix "#[fg=brightcyan]#[bg=black]#[nobold]#[noitalics]#[nounderscore]#[bg=brightcyan]#[fg=black]"
set -g @prefix_highlight_output_suffix ""
set -g @prefix_highlight_copy_mode_attr "fg=brightcyan,bg=black,bold"

set -g status-left "#[fg=black,bg=#7aa2f7] #S #[fg=#7aa2f7,bg=#1f2335,nobold,noitalics,nounderscore]"
set -g status-right "#{prefix_highlight}#[fg=#292e42,bg=#1f2335,nobold,noitalics,nounderscore]#[fg=#a9b1d6,bg=#292e42] %Y-%m-%d #[fg=#a9b1d6,bg=#292e42,nobold,noitalics,nounderscore]#[fg=#a9b1d6,bg=#292e42] %H:%M #[fg=#7aa2f7,bg=#292e42,nobold,noitalics,nounderscore]#[fg=black,bg=#7aa2f7] #H "

set -g window-status-format "#[fg=#1f2335,bg=#292e42,nobold,noitalics,nounderscore] #[fg=white,bg=#292e42]#I #[fg=white,bg=#292e42,nobold,noitalics,nounderscore] #[fg=white,bg=#292e42]#W #F #[fg=#292e42,bg=#1f2335,nobold,noitalics,nounderscore]"
set -g window-status-current-format "#[fg=#1f2335,bg=#9ece6a,nobold,noitalics,nounderscore] #[fg=black,bg=#9ece6a]#I #[fg=black,bg=#9ece6a,nobold,noitalics,nounderscore] #[fg=black,bg=#9ece6a]#W #F #[fg=#9ece6a,bg=#1f2335,nobold,noitalics,nounderscore]"
set -g window-status-separator ""

